name: CoverageSln
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests with coverage
        run: |
          dotnet test CoverageValue.sln

      - name: Generate report
        shell: bash
        run: |
          reportgenerator \
            -reports:coverage-results/*.xml \
            -targetdir:coverage-report \
            -reporttypes:TextSummary,lcov

      - name: Show coverage summary
        run: type coverage-report/Summary.txt
