name: CoverageMatrix

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - category: unit
            project: CoverageValue.Unit.Tests.csproj
          - category: component
            project: CoverageValue.Component.Tests.csproj
          - category: integration
            project: CoverageValue.Integration.Tests.csproj

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore

      - name: Create coverage-results folder
        run: mkdir -p $GITHUB_WORKSPACE/CoverageValue/coverage-results
        shell: bash

      - name: Run ${{ matrix.category }} tests with coverage
        run: |
          dotnet test "$GITHUB_WORKSPACE/CoverageValue/${{ matrix.project }}" \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput="$GITHUB_WORKSPACE/CoverageValue/coverage-results/${{ matrix.category }}.xml"
        shell: bash

      - name: Generate merged report
        run: |
          reportgenerator \
            -reports:$GITHUB_WORKSPACE/CoverageValue/coverage-results/*.xml \
            -targetdir:$GITHUB_WORKSPACE/CoverageValue/coverage-report \
            -reporttypes:TextSummary,lcov
        shell: bash

      - name: Show coverage summary
        run: cat $GITHUB_WORKSPACE/CoverageValue/coverage-report/Summary.txt
        shell: bash
